import Head from 'next/head'
import {BsMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillInstagram, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import devsoul from "../public/luanImg.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luan Alves - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-slate-900 px-10 min-h-screen'>

          <section className='min-h-3/4'>

            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl text-slate-200 font-centauri cursor-default'>Soulzin</h1>
              <ul className='flex items-center'>
                <li><BsMoonStarsFill className='cursor-pointer text-2xl text-slate-200'/></li>
                <li>
                  <a className='bg-gradient-to-tr from-purple-800 to-slate-800 text-white px-4 py-2 rounded-md ml-8 font-burtons'
                   href="#">Resume</a>
                </li>
              </ul>
            </nav>

            <div className='text-center'>
              <h2 className='text-5xl text-purple-700 font-medium  py-2'>Luan Alves</h2>
              <h3 className='text-2xl text-slate-100 py-2'>Programador</h3>
              <p className='text-lg text-slate-50 py-4'>
                Freelancer, trabalho com desenvolvimento de aplicações desktop com a linguagem
                Java, e tento desenvolver para Web.
              </p>
            </div>

            <div className='text-4xl text-center flex text-slate-50 justify-center gap-9'>
                <a href="https://www.linkedin.com/in/luan-alves-de-oliveira-80a072236/" target="_blank" rel="noopener">
                <AiFillLinkedin/>
                </a>
                <a href="https://www.instagram.com/soulzin010" target="_blank" rel="noopener">
                <AiFillInstagram/>
                </a>
                <a href="https://www.youtube.com" target='_blank' rel="noopener">
                <AiFillYoutube/>
                </a>
              </div>

              <div className="relative rounded-full w-72 h-72 overflow-clip mx-auto mt-10 border-slate-600 border-4">
                <Image className='object-cover' src={devsoul} fill/>
              </div>
          </section>
          <section>
            <div>
                <h3 className="text-3xl text-center text-slate-50">
                  Serviços que eu ofereço:
                </h3>
                <p className='text-md py-2 text-center text-slate-50'>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sed convallis nibh, a aliquet eros. 
                  Nulla semper lorem non enim venenatis sodales. Pellentesque nisi elit, lacinia cursus ante ut, faucibus sagittis ipsum.
                </p>
            </div>
          </section>
      </main>
    </div>
  )
}
